### PR TITLE
🚧 Add unit tests [wip]

### PR DESCRIPTION
**Pull request by glmn**
## Work in progress
- [ ] domain\base.py
- - [ ] Seasons
- - [ ] Playerseasons
- - [x] Leaderboard
- [x] domain\telemetry\base.py
- [x] domain\telemetry\events.py
- [x] domain\telemetry\objects.py

### CODE REVIEW

**Comment by ramonsaraiva** [comment]
Looking forward to this 🚀

**Comment by glmn** [comment]
pubg_python/domain/base.py
```python
class Season(Domain):

    def from_dict(self):
        super().from_dict()
        self.is_current_season = self.attributes.get('isCurrentSeason')
        self.is_off_season = self.attributes.get('isOffSeason')
        self.best_rank_point = self.attributes.get('bestRankPoint')```

Can't find `bestRankPoint` in documentation. May i remove this @ramonsaraiva ?

**Comment by ramonsaraiva** [comment]
I think that's unused.

**Comment by glmn** [comment]
@ramonsaraiva what is this?

**Comment by ramonsaraiva** [comment]
A mistake, was trying to trigger a rebuild from your PR after updating master's workflow. Can you force-push with your local changes?

**Comment by ramonsaraiva** [comment]
I think the workflow was not being triggered from just PRs when branches were not being created in the parent repo.

**Pull request closed without merging**
